/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GestionnairePersonnelsRouteImport } from './routes/gestionnaire.personnels'
import { Route as GestionnaireMedicamentsRouteImport } from './routes/gestionnaire.medicaments'
import { Route as GestionnaireIndicateursRouteImport } from './routes/gestionnaire.indicateurs'
import { Route as GestionnaireDashboardRouteImport } from './routes/gestionnaire.dashboard'
import { Route as GestionnaireCartographiesRouteImport } from './routes/gestionnaire.cartographies'
import { Route as AdminUtilisateursRouteImport } from './routes/admin.utilisateurs'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminEtablissementsRouteImport } from './routes/admin.etablissements'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminConsultationRouteImport } from './routes/admin.consultation'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionnairePersonnelsRoute = GestionnairePersonnelsRouteImport.update({
  id: '/gestionnaire/personnels',
  path: '/gestionnaire/personnels',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionnaireMedicamentsRoute = GestionnaireMedicamentsRouteImport.update({
  id: '/gestionnaire/medicaments',
  path: '/gestionnaire/medicaments',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionnaireIndicateursRoute = GestionnaireIndicateursRouteImport.update({
  id: '/gestionnaire/indicateurs',
  path: '/gestionnaire/indicateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionnaireDashboardRoute = GestionnaireDashboardRouteImport.update({
  id: '/gestionnaire/dashboard',
  path: '/gestionnaire/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionnaireCartographiesRoute =
  GestionnaireCartographiesRouteImport.update({
    id: '/gestionnaire/cartographies',
    path: '/gestionnaire/cartographies',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/admin/utilisateurs',
  path: '/admin/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/admin/sources',
  path: '/admin/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEtablissementsRoute = AdminEtablissementsRouteImport.update({
  id: '/admin/etablissements',
  path: '/admin/etablissements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsultationRoute = AdminConsultationRouteImport.update({
  id: '/admin/consultation',
  path: '/admin/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/consultation': typeof AdminConsultationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/etablissements': typeof AdminEtablissementsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/gestionnaire/cartographies': typeof GestionnaireCartographiesRoute
  '/gestionnaire/dashboard': typeof GestionnaireDashboardRoute
  '/gestionnaire/indicateurs': typeof GestionnaireIndicateursRoute
  '/gestionnaire/medicaments': typeof GestionnaireMedicamentsRoute
  '/gestionnaire/personnels': typeof GestionnairePersonnelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/consultation': typeof AdminConsultationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/etablissements': typeof AdminEtablissementsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/gestionnaire/cartographies': typeof GestionnaireCartographiesRoute
  '/gestionnaire/dashboard': typeof GestionnaireDashboardRoute
  '/gestionnaire/indicateurs': typeof GestionnaireIndicateursRoute
  '/gestionnaire/medicaments': typeof GestionnaireMedicamentsRoute
  '/gestionnaire/personnels': typeof GestionnairePersonnelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/consultation': typeof AdminConsultationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/etablissements': typeof AdminEtablissementsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/gestionnaire/cartographies': typeof GestionnaireCartographiesRoute
  '/gestionnaire/dashboard': typeof GestionnaireDashboardRoute
  '/gestionnaire/indicateurs': typeof GestionnaireIndicateursRoute
  '/gestionnaire/medicaments': typeof GestionnaireMedicamentsRoute
  '/gestionnaire/personnels': typeof GestionnairePersonnelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/categories'
    | '/admin/consultation'
    | '/admin/dashboard'
    | '/admin/etablissements'
    | '/admin/roles'
    | '/admin/sources'
    | '/admin/utilisateurs'
    | '/gestionnaire/cartographies'
    | '/gestionnaire/dashboard'
    | '/gestionnaire/indicateurs'
    | '/gestionnaire/medicaments'
    | '/gestionnaire/personnels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/categories'
    | '/admin/consultation'
    | '/admin/dashboard'
    | '/admin/etablissements'
    | '/admin/roles'
    | '/admin/sources'
    | '/admin/utilisateurs'
    | '/gestionnaire/cartographies'
    | '/gestionnaire/dashboard'
    | '/gestionnaire/indicateurs'
    | '/gestionnaire/medicaments'
    | '/gestionnaire/personnels'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/categories'
    | '/admin/consultation'
    | '/admin/dashboard'
    | '/admin/etablissements'
    | '/admin/roles'
    | '/admin/sources'
    | '/admin/utilisateurs'
    | '/gestionnaire/cartographies'
    | '/gestionnaire/dashboard'
    | '/gestionnaire/indicateurs'
    | '/gestionnaire/medicaments'
    | '/gestionnaire/personnels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminConsultationRoute: typeof AdminConsultationRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEtablissementsRoute: typeof AdminEtablissementsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
  GestionnaireCartographiesRoute: typeof GestionnaireCartographiesRoute
  GestionnaireDashboardRoute: typeof GestionnaireDashboardRoute
  GestionnaireIndicateursRoute: typeof GestionnaireIndicateursRoute
  GestionnaireMedicamentsRoute: typeof GestionnaireMedicamentsRoute
  GestionnairePersonnelsRoute: typeof GestionnairePersonnelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestionnaire/personnels': {
      id: '/gestionnaire/personnels'
      path: '/gestionnaire/personnels'
      fullPath: '/gestionnaire/personnels'
      preLoaderRoute: typeof GestionnairePersonnelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestionnaire/medicaments': {
      id: '/gestionnaire/medicaments'
      path: '/gestionnaire/medicaments'
      fullPath: '/gestionnaire/medicaments'
      preLoaderRoute: typeof GestionnaireMedicamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestionnaire/indicateurs': {
      id: '/gestionnaire/indicateurs'
      path: '/gestionnaire/indicateurs'
      fullPath: '/gestionnaire/indicateurs'
      preLoaderRoute: typeof GestionnaireIndicateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestionnaire/dashboard': {
      id: '/gestionnaire/dashboard'
      path: '/gestionnaire/dashboard'
      fullPath: '/gestionnaire/dashboard'
      preLoaderRoute: typeof GestionnaireDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestionnaire/cartographies': {
      id: '/gestionnaire/cartographies'
      path: '/gestionnaire/cartographies'
      fullPath: '/gestionnaire/cartographies'
      preLoaderRoute: typeof GestionnaireCartographiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/utilisateurs': {
      id: '/admin/utilisateurs'
      path: '/admin/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/admin/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/etablissements': {
      id: '/admin/etablissements'
      path: '/admin/etablissements'
      fullPath: '/admin/etablissements'
      preLoaderRoute: typeof AdminEtablissementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/consultation': {
      id: '/admin/consultation'
      path: '/admin/consultation'
      fullPath: '/admin/consultation'
      preLoaderRoute: typeof AdminConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminConsultationRoute: AdminConsultationRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEtablissementsRoute: AdminEtablissementsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
  GestionnaireCartographiesRoute: GestionnaireCartographiesRoute,
  GestionnaireDashboardRoute: GestionnaireDashboardRoute,
  GestionnaireIndicateursRoute: GestionnaireIndicateursRoute,
  GestionnaireMedicamentsRoute: GestionnaireMedicamentsRoute,
  GestionnairePersonnelsRoute: GestionnairePersonnelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
